### PR TITLE
Minor changes and typos

### LINKED ISSUE #326: A typo in the introduction part
Just a small type for the record:I read from here: https://datacarpentry.org/shell-genomics/ In the section "There are several reasons to learn how to use the CLI:" in the second point the word should be tedious instead of "tedius".

### LINKED ISSUE #329: Typos in Introducing the Shell lesson, How to access the shell section
In both the second sentence and the last sentence of the second paragraph, update "sever" to "server". Also, in the last sentence, change "let's" to "lets".

When we say a ‘remote **server**’, we are talking about a computer that is not the one you are working on right now.

A ‘ready-to-go’ **server lets** us focus on learning.

### PR DESCRIPTION
**Pull request by martinosorb**
A few minor changes:

- In the index's introductory explanation there were at least a couple of typos. Fixes #326.
- The same introduction had some unclear 'etc.' and less polished language that I edited.
- Braces are not usually called "squiggle braces". I Googled this expression and it's essentially only found in that Carpentries lesson. I edited to "curly brackets", which is the common name of braces in British English.
- The wording "standard QWERTY keyboard" is incorrect and also not inclusive. There is no standard QWERTY. I edited to clarify, although it's impossible to give a comprehensive instruction on where the `|` key is on all keyboard layouts.
- I edited an exercise adding a line to the solution rather than as a comment after the exercise.
- Typos in episode 1, fixes #329

### CODE REVIEW

**Review by tobyhodges — CHANGES_REQUESTED** [review]
I'm processing outstanding pull requests on this repository, in preparation for [transition to the new lesson infrastructure](https://carpentries.github.io/workbench/faq.html#update-fork-from-styles). Thank you for contributing these improvements, @martinosorb. 

I am ambivalent about the addition of "software" to the list on line 9 of `index.md`, but otherwise I think the changes are clearly for the better. 

However, some conflicts have been introduced in the time since the PR was opened. If you can resolve these before the infrastructure transition takes place at the end of the month, I will be delighted to merge.

**Comment by martinosorb** [comment]
The "software" part was meant to say that programs also have command line interfaces, rather than being "apps" with a GUI and that kind of stuff. How about "commands" or "programs"?

**Comment by tobyhodges** [comment]
Oh ok, I think I understand better now - I think this was a misunderstanding on my part, rather than something that needs to be improved in your wording.

Thanks for resolving the conflicts - I am going to merge the PR now.

**Review by tobyhodges — APPROVED** [review]

**Comment by martinosorb** [comment]
Thank you!

**Pull request merged**
