### PR TITLE
change wording in 03 backup example

### PR DESCRIPTION
**Pull request by hoytpr**
Change example wording to "create a backup of your files using `cp`.

### CODE REVIEW

**Comment by aschuerch** [comment]
LGTM!

**Comment by hoytpr** [comment]
These should work, but solutions for #241  are not "1." and "2." but bulleted. 
See: https://hoytpr.github.io/shell-genomics/04-redirection/index.html

**Comment by aschuerch** [comment]
Addresses issues #243 #242 #241 #239, correct @hoytpr ? 
LGTM. 
Can you, @swang8 or @ryneches review as well and merge?

**Comment by hoytpr** [comment]
Yes, @aschuerch those are the issues addressed. Next PR will be cleaner.

**Pull request merged**
