### PR TITLE
change image from owner/user to user/other, issue  #308

### PR DESCRIPTION
**Pull request by NadineBestard**
I was not familar with the svg format, so it would be important to check my new image works. 
I took it from here:
https://www.booleanworld.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2018/04/classes.png.webp

### CODE REVIEW

**Comment by akshayparopkari** [comment]
Thank you for the PR, @NadineBestard 

Unfortunately, I am unable to view the image. The URL returns a 404 error for me - _The page you are trying to reach does not exist, or has been moved. Please use the menus or the search box to find what you are looking for._

Do you have another avenue for sharing the image?

**Comment by akshayparopkari** [comment]
I was able to view the image here via GitHub - https://raw.githubusercontent.com/NadineBestard/shell-genomics/0bfc568d746998aef99a48042183353a27669d82/fig/rwx_figure.svg

Looks good to me 👍

What do you think, @datacarpentry/shell-genomics-maintainers?

**Comment by NadineBestard** [comment]
Yep, does not really matter if the original image is not there anymore; as I transformed that image to a svg format, and this is what I used to replace the existing image.

**Comment by aschuerch** [comment]
LGTM

**Pull request merged**
