### PR TITLE
Enable menu to select platform

### PR DESCRIPTION
**Pull request by ErinBecker**
Partial fix for https://github.com/datacarpentry/shell-genomics/issues/186

I've added the code to get the menu to work (I think), but as far as I can tell, the content for the section "Uploading Data to your Virtual Machine" for Unix is missing. This PR should **NOT** be merged without adding that content first. I haven't used scp in years. Anyone who can help add this content?

### CODE REVIEW

**Comment by ErinBecker** [comment]
Maybe @ACharbonneau or @taylorreiter could point me towards an older version of these instructions? I can type up the actual changes if someone can point me in the right direction. 🙂

**Comment by ACharbonneau** [comment]
I think this is from a page originally called something like 'data roundtripping'. I'll see if I can find it

**Comment by ACharbonneau** [comment]
and I can write/re-write the scp part

**Comment by ACharbonneau** [comment]
If this came from the cloud-genomics lesson, it would be based on this: https://github.com/datacarpentry/cloud-genomics/blob/527ab4b3172cbb417db88ba51c612f803ce027e9/_episodes/04-data-roundtripping.md

**Comment by ErinBecker** [comment]
Thanks @ACharbonneau for tracking that down! If you were ok with writing/rewriting the scp section, that would be fantastic. But I'm also available to help out if needed. Please just let me know. I'll take my cue from who you decide to assign this issue too. :-)

**Comment by ACharbonneau** [comment]
ugh. I tried to just edit this PR, but it made a new one. Editing must be locked :( 
I did use this PR as the base for https://github.com/datacarpentry/shell-genomics/pull/215 though, so you can safely merge 215 rather than this one and still get all Erin's changes.

**Comment by ACharbonneau** [comment]
Incidentally, I also don't have privileges to assign myself to PRs in this repo, so sorry if it looked like I just disappeared :/

**Comment by ACharbonneau** [comment]
Sorry, one more comment. I could *only* get this page to render locally to test the selection code by physically copying the entire page into my local cloud-genomics repo and rendering that. This shell-genomics repo just would not render no matter what I did. I'm not familiar enough with Jekyll to suggest any fixes, but I don't think it's a problem with my install because I can render cloud-genomics just fine. Here's the error I'm getting:

**Comment by ErinBecker** [comment]
Replaced by #215.

**Pull request closed without merging**
