### PR TITLE
Added an instruction for rm - Fixes issue #240

### LINKED ISSUE #240: Adding an instruction during `rm`
During the lesson on `rm`, the lessons says:
"If you enter n (for no), the file will not be deleted. If you enter y, you will delete the file. This gives us an extra measure of security, as there is one more step between us and deleting our data files."

A statement saying "You should enter `n` for now." should be inserted so that the following `rm -r backup` will work as expected.

### PR DESCRIPTION
**Pull request by nairps**
Fixes #240

### CODE REVIEW

**Comment by akshayparopkari** [comment]
Looks good to me 👍

**Comment by akshayparopkari** [comment]
I will wait for a couple of days in case @datacarpentry/shell-genomics-maintainers have any inputs, before merging this PR.

**Review by akshayparopkari — APPROVED** [review]

**Comment by aschuerch** [comment]
Useful addition, thank you @nairps . I corrected (I guess) a typo. Please have a look @nairps in "Files changed" or "Commits"

**Comment by akshayparopkari** [comment]
@datacarpentry/shell-genomics-maintainers, is this PR ready to be merged?

**Comment by esallychang** [comment]
Since both other @datacarpentry/shell-genomics-maintainers tagged here seem to like this PR and it looked good to me, went ahead and merged.

**Pull request merged**
