### PR TITLE
Fix #339 to correct contributing links

### LINKED ISSUE #339: Links need to be fixed in CONTRIBUTING.md
The Contributing Guide, `CONTRIBUTING.md`, contains two links with URLs that should be updated:

1. the _How to Contribute to an Open Source Project on GitHub_ link leads to a 404 and should be updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
2. the `[repo]` link reference currently points to a placeholder URL (https://example.com/FIXME) and should be updated to point to the source repository for the lesson (i.e. this GitHub repository).

The Contributing Guide is one of the files that is unique to each repository - to allow for individual lesson projects to define their own guidance for contributors - so unfortunately this is not an issue that can be fixed centrally e.g. by updating the template files in the lesson infrastructure. Instead the file must be updated in the individual lesson repositories themselves.

### PR DESCRIPTION
**Pull request by cpauvert**
Fixes #339

### CODE REVIEW

**Comment by cpauvert** [comment]
I'm sorry, the a3d0daec97705dbd52c39b89b2e101f6d1dd6ad2 commit was reverted as it is safer belonging in a different PR (#342 ), in case the maintainers do not agree with the proposed changes.
This could be squashed on my side.
BEst,

**Review by p-j-smith — APPROVED** [review]
thanks for the fix @cpauvert !

**Comment by p-j-smith** [comment]
Before I merge, please could you edit the comment at the top of this PR to say 'Fixes #339' - this way the issue will automatically be closed when the pr is merged. Thanks!

> I'm sorry, the https://github.com/datacarpentry/shell-genomics/commit/a3d0daec97705dbd52c39b89b2e101f6d1dd6ad2 commit was reverted as it is safer belonging in a different PR (https://github.com/datacarpentry/shell-genomics/pull/342 ), in case the maintainers do not agree with the proposed changes.
This could be squashed on my side.
BEst,

And no worries about this, I can squash when merging the PR

**Comment by cpauvert** [comment]
> Before I merge, please could you edit the comment at the top of this PR to say 'Fixes #339' - this way the issue will automatically be closed when the pr is merged. Thanks!
Done!


> And no worries about this, I can squash when merging the PR

True! Good idea!

**Comment by p-j-smith** [comment]
thanks @cpauvert !

**Pull request merged**
